In [53]:
import pandas as pd;

In [54]:
df=pd.read_csv("../data/TorontoWeather/TorontoWeatherData.csv",parse_dates=['Date'])

In [55]:
df

,Station Name,Date,Max Temp (°C),Min Temp (°C),Snow on Grnd (cm),Type
0,TORONTO CITY,2024-01-01,-0.7,-3.1,2.0,Sunny
1,TORONTO CITY,2024-01-04,NaN,-6.0,NaN,Snowy
2,TORONTO CITY,2024-01-05,0.4,-2.1,4.0,Snowy
3,TORONTO CITY,2024-01-06,2.1,NaN,5.0,Snowy
4,TORONTO CITY,2024-01-07,0.7,-4.2,5.0,Sunny
5,TORONTO CITY,2024-01-12,3.9,NaN,8.0,Snowy
6,TORONTO CITY,2024-01-13,6.8,-2.9,10.0,Snowy
7,TORONTO CITY,2024-01-14,NaN,-11.2,8.0,Sunny
8,TORONTO CITY,2024-01-15,-7.1,NaN,NaN,Snowy

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Station Name       9 non-null      object
 1   Date               9 non-null      datetime64[ns]
 2   Max Temp (°C)      7 non-null      float64
 3   Min Temp (°C)      6 non-null      float64
 4   Snow on Grnd (cm)  7 non-null      float64
 5   Type               9 non-null      object
dtypes: datetime64[ns](1), float64(3), object(2)
memory usage: 560.0+ bytes

In [57]:
df.set_index('Date', inplace=True)

In [58]:
df

,Station Name,Max Temp (°C),Min Temp (°C),Snow on Grnd (cm),Type
Date,,,,,
2024-01-01,TORONTO CITY,-0.7,-3.1,2.0,Sunny
2024-01-04,TORONTO CITY,NaN,-6.0,NaN,Snowy
2024-01-05,TORONTO CITY,0.4,-2.1,4.0,Snowy
2024-01-06,TORONTO CITY,2.1,NaN,5.0,Snowy
2024-01-07,TORONTO CITY,0.7,-4.2,5.0,Sunny
2024-01-12,TORONTO CITY,3.9,NaN,8.0,Snowy
2024-01-13,TORONTO CITY,6.8,-2.9,10.0,Snowy
2024-01-14,TORONTO CITY,NaN,-11.2,8.0,Sunny
2024-01-15,TORONTO CITY,-7.1,NaN,NaN,Snowy

In [59]:
df1 = df.fillna(0)
df1

,Station Name,Max Temp (°C),Min Temp (°C),Snow on Grnd (cm),Type
Date,,,,,
2024-01-01,TORONTO CITY,-0.7,-3.1,2.0,Sunny
2024-01-04,TORONTO CITY,0.0,-6.0,0.0,Snowy
2024-01-05,TORONTO CITY,0.4,-2.1,4.0,Snowy
2024-01-06,TORONTO CITY,2.1,0.0,5.0,Snowy
2024-01-07,TORONTO CITY,0.7,-4.2,5.0,Sunny
2024-01-12,TORONTO CITY,3.9,0.0,8.0,Snowy
2024-01-13,TORONTO CITY,6.8,-2.9,10.0,Snowy
2024-01-14,TORONTO CITY,0.0,-11.2,8.0,Sunny
2024-01-15,TORONTO CITY,-7.1,0.0,0.0,Snowy

In [60]:
df2 = df.fillna({
    "Max Temp (°C)":0,
    "Min Temp (°C)":0,
    "Snow on Grnd (cm)":0
})
df2

,Station Name,Max Temp (°C),Min Temp (°C),Snow on Grnd (cm),Type
Date,,,,,
2024-01-01,TORONTO CITY,-0.7,-3.1,2.0,Sunny
2024-01-04,TORONTO CITY,0.0,-6.0,0.0,Snowy
2024-01-05,TORONTO CITY,0.4,-2.1,4.0,Snowy
2024-01-06,TORONTO CITY,2.1,0.0,5.0,Snowy
2024-01-07,TORONTO CITY,0.7,-4.2,5.0,Sunny
2024-01-12,TORONTO CITY,3.9,0.0,8.0,Snowy
2024-01-13,TORONTO CITY,6.8,-2.9,10.0,Snowy
2024-01-14,TORONTO CITY,0.0,-11.2,8.0,Sunny
2024-01-15,TORONTO CITY,-7.1,0.0,0.0,Snowy

In [61]:
df3 = df.fillna(method='ffill')
df3

/var/folders/2v/jpd863_n53d9410dln88s25m0000gn/T/ipykernel_79311/627673650.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df3 = df.fillna(method='ffill')

,Station Name,Max Temp (°C),Min Temp (°C),Snow on Grnd (cm),Type
Date,,,,,
2024-01-01,TORONTO CITY,-0.7,-3.1,2.0,Sunny
2024-01-04,TORONTO CITY,-0.7,-6.0,2.0,Snowy
2024-01-05,TORONTO CITY,0.4,-2.1,4.0,Snowy
2024-01-06,TORONTO CITY,2.1,-2.1,5.0,Snowy
2024-01-07,TORONTO CITY,0.7,-4.2,5.0,Sunny
2024-01-12,TORONTO CITY,3.9,-4.2,8.0,Snowy
2024-01-13,TORONTO CITY,6.8,-2.9,10.0,Snowy
2024-01-14,TORONTO CITY,6.8,-11.2,8.0,Sunny
2024-01-15,TORONTO CITY,-7.1,-11.2,8.0,Snowy

In [62]:
df3 = df.fillna(method='ffill',axis="rows")
df3

/var/folders/2v/jpd863_n53d9410dln88s25m0000gn/T/ipykernel_79311/2638398840.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df3 = df.fillna(method='ffill',axis="rows")

,Station Name,Max Temp (°C),Min Temp (°C),Snow on Grnd (cm),Type
Date,,,,,
2024-01-01,TORONTO CITY,-0.7,-3.1,2.0,Sunny
2024-01-04,TORONTO CITY,-0.7,-6.0,2.0,Snowy
2024-01-05,TORONTO CITY,0.4,-2.1,4.0,Snowy
2024-01-06,TORONTO CITY,2.1,-2.1,5.0,Snowy
2024-01-07,TORONTO CITY,0.7,-4.2,5.0,Sunny
2024-01-12,TORONTO CITY,3.9,-4.2,8.0,Snowy
2024-01-13,TORONTO CITY,6.8,-2.9,10.0,Snowy
2024-01-14,TORONTO CITY,6.8,-11.2,8.0,Sunny
2024-01-15,TORONTO CITY,-7.1,-11.2,8.0,Snowy

In [63]:
df

,Station Name,Max Temp (°C),Min Temp (°C),Snow on Grnd (cm),Type
Date,,,,,
2024-01-01,TORONTO CITY,-0.7,-3.1,2.0,Sunny
2024-01-04,TORONTO CITY,NaN,-6.0,NaN,Snowy
2024-01-05,TORONTO CITY,0.4,-2.1,4.0,Snowy
2024-01-06,TORONTO CITY,2.1,NaN,5.0,Snowy
2024-01-07,TORONTO CITY,0.7,-4.2,5.0,Sunny
2024-01-12,TORONTO CITY,3.9,NaN,8.0,Snowy
2024-01-13,TORONTO CITY,6.8,-2.9,10.0,Snowy
2024-01-14,TORONTO CITY,NaN,-11.2,8.0,Sunny
2024-01-15,TORONTO CITY,-7.1,NaN,NaN,Snowy

In [64]:
df['Min Temp (°C) FFILL'] = df.groupby('Type')['Min Temp (°C)'].fillna(method='ffill')

/var/folders/2v/jpd863_n53d9410dln88s25m0000gn/T/ipykernel_79311/192888159.py:1: FutureWarning: SeriesGroupBy.fillna is deprecated and will be removed in a future version. Use obj.ffill() or obj.bfill() for forward or backward filling instead. If you want to fill with a single value, use Series.fillna instead
  df['Min Temp (°C) FFILL'] = df.groupby('Type')['Min Temp (°C)'].fillna(method='ffill')
/var/folders/2v/jpd863_n53d9410dln88s25m0000gn/T/ipykernel_79311/192888159.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Min Temp (°C) FFILL'] = df.groupby('Type')['Min Temp (°C)'].fillna(method='ffill')

In [65]:
df

,Station Name,Max Temp (°C),Min Temp (°C),Snow on Grnd (cm),Type,Min Temp (°C) FFILL
Date,,,,,,
2024-01-01,TORONTO CITY,-0.7,-3.1,2.0,Sunny,-3.1
2024-01-04,TORONTO CITY,NaN,-6.0,NaN,Snowy,-6.0
2024-01-05,TORONTO CITY,0.4,-2.1,4.0,Snowy,-2.1
2024-01-06,TORONTO CITY,2.1,NaN,5.0,Snowy,-2.1
2024-01-07,TORONTO CITY,0.7,-4.2,5.0,Sunny,-4.2
2024-01-12,TORONTO CITY,3.9,NaN,8.0,Snowy,-2.1
2024-01-13,TORONTO CITY,6.8,-2.9,10.0,Snowy,-2.9
2024-01-14,TORONTO CITY,NaN,-11.2,8.0,Sunny,-11.2
2024-01-15,TORONTO CITY,-7.1,NaN,NaN,Snowy,-2.9

In [66]:
df['Max Temp (°C) FFILL'] = df.groupby('Type')['Max Temp (°C)'].fillna(method='ffill')
df

/var/folders/2v/jpd863_n53d9410dln88s25m0000gn/T/ipykernel_79311/2016920259.py:1: FutureWarning: SeriesGroupBy.fillna is deprecated and will be removed in a future version. Use obj.ffill() or obj.bfill() for forward or backward filling instead. If you want to fill with a single value, use Series.fillna instead
  df['Max Temp (°C) FFILL'] = df.groupby('Type')['Max Temp (°C)'].fillna(method='ffill')
/var/folders/2v/jpd863_n53d9410dln88s25m0000gn/T/ipykernel_79311/2016920259.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Max Temp (°C) FFILL'] = df.groupby('Type')['Max Temp (°C)'].fillna(method='ffill')

,Station Name,Max Temp (°C),Min Temp (°C),Snow on Grnd (cm),Type,Min Temp (°C) FFILL,Max Temp (°C) FFILL
Date,,,,,,,
2024-01-01,TORONTO CITY,-0.7,-3.1,2.0,Sunny,-3.1,-0.7
2024-01-04,TORONTO CITY,NaN,-6.0,NaN,Snowy,-6.0,NaN
2024-01-05,TORONTO CITY,0.4,-2.1,4.0,Snowy,-2.1,0.4
2024-01-06,TORONTO CITY,2.1,NaN,5.0,Snowy,-2.1,2.1
2024-01-07,TORONTO CITY,0.7,-4.2,5.0,Sunny,-4.2,0.7
2024-01-12,TORONTO CITY,3.9,NaN,8.0,Snowy,-2.1,3.9
2024-01-13,TORONTO CITY,6.8,-2.9,10.0,Snowy,-2.9,6.8
2024-01-14,TORONTO CITY,NaN,-11.2,8.0,Sunny,-11.2,0.7
2024-01-15,TORONTO CITY,-7.1,NaN,NaN,Snowy,-2.9,-7.1

In [67]:
df['Max Temp (°C) BFILL'] = df.groupby('Type')['Max Temp (°C)'].fillna(method='bfill')
df

/var/folders/2v/jpd863_n53d9410dln88s25m0000gn/T/ipykernel_79311/1153932188.py:1: FutureWarning: SeriesGroupBy.fillna is deprecated and will be removed in a future version. Use obj.ffill() or obj.bfill() for forward or backward filling instead. If you want to fill with a single value, use Series.fillna instead
  df['Max Temp (°C) BFILL'] = df.groupby('Type')['Max Temp (°C)'].fillna(method='bfill')
/var/folders/2v/jpd863_n53d9410dln88s25m0000gn/T/ipykernel_79311/1153932188.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Max Temp (°C) BFILL'] = df.groupby('Type')['Max Temp (°C)'].fillna(method='bfill')

,Station Name,Max Temp (°C),Min Temp (°C),Snow on Grnd (cm),Type,Min Temp (°C) FFILL,Max Temp (°C) FFILL,Max Temp (°C) BFILL
Date,,,,,,,,
2024-01-01,TORONTO CITY,-0.7,-3.1,2.0,Sunny,-3.1,-0.7,-0.7
2024-01-04,TORONTO CITY,NaN,-6.0,NaN,Snowy,-6.0,NaN,0.4
2024-01-05,TORONTO CITY,0.4,-2.1,4.0,Snowy,-2.1,0.4,0.4
2024-01-06,TORONTO CITY,2.1,NaN,5.0,Snowy,-2.1,2.1,2.1
2024-01-07,TORONTO CITY,0.7,-4.2,5.0,Sunny,-4.2,0.7,0.7
2024-01-12,TORONTO CITY,3.9,NaN,8.0,Snowy,-2.1,3.9,3.9
2024-01-13,TORONTO CITY,6.8,-2.9,10.0,Snowy,-2.9,6.8,6.8
2024-01-14,TORONTO CITY,NaN,-11.2,8.0,Sunny,-11.2,0.7,NaN
2024-01-15,TORONTO CITY,-7.1,NaN,NaN,Snowy,-2.9,-7.1,-7.1

In [68]:
df['Max Temp (°C) NoZero'] = df.groupby('Type')['Max Temp (°C) BFILL'].fillna(method='ffill')
df

/var/folders/2v/jpd863_n53d9410dln88s25m0000gn/T/ipykernel_79311/171960839.py:1: FutureWarning: SeriesGroupBy.fillna is deprecated and will be removed in a future version. Use obj.ffill() or obj.bfill() for forward or backward filling instead. If you want to fill with a single value, use Series.fillna instead
  df['Max Temp (°C) NoZero'] = df.groupby('Type')['Max Temp (°C) BFILL'].fillna(method='ffill')
/var/folders/2v/jpd863_n53d9410dln88s25m0000gn/T/ipykernel_79311/171960839.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Max Temp (°C) NoZero'] = df.groupby('Type')['Max Temp (°C) BFILL'].fillna(method='ffill')

,Station Name,Max Temp (°C),Min Temp (°C),Snow on Grnd (cm),Type,Min Temp (°C) FFILL,Max Temp (°C) FFILL,Max Temp (°C) BFILL,Max Temp (°C) NoZero
Date,,,,,,,,,
2024-01-01,TORONTO CITY,-0.7,-3.1,2.0,Sunny,-3.1,-0.7,-0.7,-0.7
2024-01-04,TORONTO CITY,NaN,-6.0,NaN,Snowy,-6.0,NaN,0.4,0.4
2024-01-05,TORONTO CITY,0.4,-2.1,4.0,Snowy,-2.1,0.4,0.4,0.4
2024-01-06,TORONTO CITY,2.1,NaN,5.0,Snowy,-2.1,2.1,2.1,2.1
2024-01-07,TORONTO CITY,0.7,-4.2,5.0,Sunny,-4.2,0.7,0.7,0.7
2024-01-12,TORONTO CITY,3.9,NaN,8.0,Snowy,-2.1,3.9,3.9,3.9
2024-01-13,TORONTO CITY,6.8,-2.9,10.0,Snowy,-2.9,6.8,6.8,6.8
2024-01-14,TORONTO CITY,NaN,-11.2,8.0,Sunny,-11.2,0.7,NaN,0.7
2024-01-15,TORONTO CITY,-7.1,NaN,NaN,Snowy,-2.9,-7.1,-7.1,-7.1